# Generated by Django 2.0.2 on 2018-03-06 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts', '0002_auto_20180306_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='asusscore',
            name='clientid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cts.Clients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programs',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='USERID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cts.Clients'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='clientid',
            field=models.ForeignKey(db_column='CLIENTID', on_delete=django.db.models.deletion.CASCADE, to='cts.Clients'),
        ),
    ]
