# Generated by Django 2.0.2 on 2018-03-27 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cts', '0003_auto_20180306_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violations',
            name='viouserid',
            field=models.ForeignKey(blank=True, db_column='VIOUSERID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cts.Clients'),
        ),
    ]
